[package]

name = "bmstu-cg-courseProject-5th-sem"
version = "0.1.1"
edition = "2021"
build = "src/app_factory/slint/build.rs"
authors = ["archeoss <archeosAnacritis@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
optimize = ["log/release_max_level_warn"]
web = ["wgpu/webgl"]
default = ["optimize"]

[dependencies]
slint = "0.2.5"
raw-window-handle = "0.5.0"
async-trait = "0.1.57"
log = "0.4"
pixels = "0.9.0"
wgpu = "0.12"
winit = "0.26"
winit_input_helper = "0.12"
futures = "0.3.21"

[build-dependencies]
slint-build = "0.2.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
wasm-bindgen = "0.2.78"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.9"
pollster = "0.2"