[package]

name = "bmstu-cg-courseProject-5th-sem"
version = "0.1.0"
edition = "2021"
authors = ["archeoss <archeosAnacritis@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#qt_widgets = "0.5"
sdl2 = "0.5.0"
