import { Button, VerticalBox, LineEdit, StandardButton } from "std-widgets.slint";

export global err_dialog := Rectangle {
        z: 1;
    property <bool> err_visible;
    property <string> error_text <=> err_text.text;
    HorizontalLayout {
        alignment: center;
        VerticalLayout {
            alignment: center;
            Rectangle {
                background: white;
                visible: err_visible;
                ErrorDialog := Dialog {
                    visible: err_visible;
                    VerticalBox {
                        alignment: start;
                        err_text := Text {
                        }
                        Button { text: "close"; clicked => {err_visible = false;} }
                    }
                }
            }
        }
    }
}